---
title: "Mateusz Staniak"
author: "Automated/Quick EDA in R: an example based on COMPAS data"
date: "`r format(Sys.time(), '%d %m, %Y')`"
output:
  html_document:
    df_print: paged
    toc: true
    toc_float: true
    code_folding: hide
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      cache = TRUE)
library(tidyverse)
library(tableone)
library(mlr)
library(rms)
library(DataExplorer)
library(broom)
```

```{r }
dataMaid::makeDataReport(recid)

n_distinct(recid$c_charge_desc)

library(ggplot2)

ggplot(recid, aes(x = is_recid, fill = c_charge_degree)) +
  geom_bar(position = "dodge") +
  theme_bw()

ggplot(recid, aes(y = jail_days, x = is_recid)) +
  geom_boxplot() +
  theme_bw()

ggplot(recid, aes(x = jail_days, fill = is_recid)) +
  geom_histogram() +
  theme_bw()


plot_missing(recid)
dataMaid::check(recid)

plot_correlation(recid, cor_args = list(use = "complete.obs"))

recid <- select(recid, -age_at_offense)

plot_bar(recid)

recid_small <- select(recid,
                      age, race, priors_count, is_recid, jail_days)

plot_bar(recid_small)
plot_histogram(recid_small)
plot_histogram(mutate(recid_small, log_count = log(priors_count + 1)))

plot_correlation(recid_small)
visdat::vis_cor(select_if(recid_small, is.numeric))

recid_small <- mutate(recid_small,
                      priors_cat = arules::discretize(priors_count, method = "cluster"),
                      jail_days_cat = arules::discretize(jail_days, method = "cluster"))
plot_bar(recid_small)

recid_small %>%
  mutate(race = as.character(race)) %>%
  mutate(race = if_else(race %in% c("African-American", "Caucasian"),
                                 race,
                                 "Other")) %>%
  mutate(is_recid = if_else(is_recid == 1, "yes", "no")) %>%
  group_by(race) %>%
  mutate(race_count = n()) %>%
  ggplot(aes(x = reorder(race, -race_count), fill = is_recid)) +
  geom_bar(position = "dodge") +
  theme_bw() +
  xlab("race") +
  guides(fill = guide_legend(title = "is recidivist"))

ggplot(recid_small, aes(x = age, fill = is_recid)) +
  geom_density(alpha = 0.6)

recid_task <- makeClassifTask(id = "compass",
                              data = select(recid_small, -priors_cat, -jail_days),
                              target = "is_recid")
recid_task2 <- makeClassifTask(id = "compass2",
                               data = select(recid_small, -priors_count, -jail_days),
                               target = "is_recid")
recid_task3 <- makeClassifTask(id = "compass3",
                               data = mutate(recid_small,
                                             race = as.factor(ifelse(race %in% c("African-American", "Caucasian"),
                                                           race,
                                                           "Other"))),
                               target = "is_recid")

por_proste <- benchmark(
  makeLearners(c("logreg", "randomForest"), type = "classif", predict.type = "prob"),
  list(recid_task, recid_task2, recid_task3),
  cv10,
  measures = auc)
plotBMRBoxplots(por_proste)
```

```{r }

recid_small <- select(recid,
                      age, race, priors_count, is_recid)

recid_small <- mutate(recid_small,
                      priors_cat = arules::discretize(priors_count, method = "cluster"))


recid_small <- recid_small %>%
  mutate(race = as.character(race)) %>%
  mutate(race = if_else(race %in% c("African-American", "Caucasian"),
                        race,
                        "Other")) 

prop.table(table(recid_small$race, ifelse(recid_small$is_recid==1, "recydywa", "nie")), margin = 1)


overview <- autoEDA(recid_small, y = "is_recid", outputPath = ".")
```

# R Information

```{r }
devtools::session_info()
```

