\documentclass[]{report}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={example\_data},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{longtable,booktabs}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{example\_data}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
  \subtitle{Autogenerated data summary from dataMaid}
  \author{}
    \preauthor{}\postauthor{}
      \predate{\centering\large\emph}
  \postdate{\par}
    \date{2019-03-15 15:44:47}

\renewcommand{\chaptername}{Part}
\newcommand{\fullline}{\noindent\makebox[\linewidth]{\rule{\textwidth}{0.4pt}}}
\newcommand{\bminione}{\begin{minipage}{0.75 \textwidth}}
\newcommand{\bminitwo}{\begin{minipage}{0.25 \textwidth}}
\newcommand{\emini}{\end{minipage}}

\begin{document}
\maketitle

\chapter{Data report overview}\label{data-report-overview}

The dataset examined has the following dimensions:

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.33\columnwidth}\raggedright\strut
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.10\columnwidth}\raggedleft\strut
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.33\columnwidth}\raggedright\strut
Number of observations\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedleft\strut
1000\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.33\columnwidth}\raggedright\strut
Number of variables\strut
\end{minipage} & \begin{minipage}[t]{0.10\columnwidth}\raggedleft\strut
9\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\subsection{Checks performed}\label{checks-performed}

The following variable checks were performed, depending on the data type
of each variable:

\begin{longtable}[]{@{}lcccccccc@{}}
\toprule
\begin{minipage}[b]{0.28\columnwidth}\raggedright\strut
~\strut
\end{minipage} & \begin{minipage}[b]{0.06\columnwidth}\centering\strut
character\strut
\end{minipage} & \begin{minipage}[b]{0.06\columnwidth}\centering\strut
factor\strut
\end{minipage} & \begin{minipage}[b]{0.06\columnwidth}\centering\strut
labelled\strut
\end{minipage} & \begin{minipage}[b]{0.09\columnwidth}\centering\strut
haven labelled\strut
\end{minipage} & \begin{minipage}[b]{0.06\columnwidth}\centering\strut
numeric\strut
\end{minipage} & \begin{minipage}[b]{0.06\columnwidth}\centering\strut
integer\strut
\end{minipage} & \begin{minipage}[b]{0.05\columnwidth}\centering\strut
logical\strut
\end{minipage} & \begin{minipage}[b]{0.05\columnwidth}\centering\strut
Date\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.28\columnwidth}\raggedright\strut
Identify miscoded missing values\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering\strut
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering\strut
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering\strut
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering\strut
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering\strut
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering\strut
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering\strut
\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering\strut
\(\times\)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.28\columnwidth}\raggedright\strut
Identify prefixed and suffixed whitespace\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering\strut
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering\strut
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering\strut
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering\strut
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering\strut
\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering\strut
\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering\strut
\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering\strut
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.28\columnwidth}\raggedright\strut
Identify levels with \textless{} 6 obs.\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering\strut
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering\strut
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering\strut
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering\strut
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering\strut
\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering\strut
\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering\strut
\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering\strut
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.28\columnwidth}\raggedright\strut
Identify case issues\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering\strut
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering\strut
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering\strut
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering\strut
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering\strut
\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering\strut
\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering\strut
\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering\strut
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.28\columnwidth}\raggedright\strut
Identify misclassified numeric or integer variables\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering\strut
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering\strut
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering\strut
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering\strut
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering\strut
\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering\strut
\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering\strut
\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering\strut
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.28\columnwidth}\raggedright\strut
Identify outliers\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering\strut
\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering\strut
\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering\strut
\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\centering\strut
\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering\strut
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\centering\strut
\(\times\)\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering\strut
\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\centering\strut
\(\times\)\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

Please note that all numerical values in the following have been rounded
to 2 decimals.

\chapter{Summary table}\label{summary-table}

\begin{longtable}[]{@{}llrrc@{}}
\toprule
\begin{minipage}[b]{0.16\columnwidth}\raggedright\strut
~\strut
\end{minipage} & \begin{minipage}[b]{0.16\columnwidth}\raggedright\strut
Variable class\strut
\end{minipage} & \begin{minipage}[b]{0.17\columnwidth}\raggedleft\strut
\# unique values\strut
\end{minipage} & \begin{minipage}[b]{0.22\columnwidth}\raggedleft\strut
Missing observations\strut
\end{minipage} & \begin{minipage}[b]{0.14\columnwidth}\centering\strut
Any problems?\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.16\columnwidth}\raggedright\strut
\protect\hyperlink{id}{ID}\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedright\strut
character\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft\strut
1000\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft\strut
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\centering\strut
\(\times\)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.16\columnwidth}\raggedright\strut
\protect\hyperlink{race}{Race}\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedright\strut
factor\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft\strut
8\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft\strut
10.70 \%\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\centering\strut
\(\times\)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.16\columnwidth}\raggedright\strut
\protect\hyperlink{age}{Age}\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedright\strut
character\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft\strut
17\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft\strut
12.20 \%\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\centering\strut
\(\times\)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.16\columnwidth}\raggedright\strut
\protect\hyperlink{sex}{Sex}\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedright\strut
factor\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft\strut
2\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft\strut
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\centering\strut
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.16\columnwidth}\raggedright\strut
\protect\hyperlink{height_cm_}{Height\_cm\_}\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedright\strut
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft\strut
365\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft\strut
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\centering\strut
\(\times\)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.16\columnwidth}\raggedright\strut
\protect\hyperlink{iq}{IQ}\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedright\strut
numeric\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft\strut
58\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft\strut
10.20 \%\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\centering\strut
\(\times\)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.16\columnwidth}\raggedright\strut
\protect\hyperlink{smokes}{Smokes}\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedright\strut
logical\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft\strut
2\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft\strut
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\centering\strut
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.16\columnwidth}\raggedright\strut
\protect\hyperlink{income}{Income}\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedright\strut
factor\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft\strut
901\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft\strut
10.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\centering\strut
\(\times\)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.16\columnwidth}\raggedright\strut
\protect\hyperlink{died}{Died}\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedright\strut
logical\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft\strut
2\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft\strut
0.00 \%\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\centering\strut
\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\chapter{Variable list}\label{variable-list}

\hypertarget{id}{\section{ID}\label{id}}

\begin{itemize}
\tightlist
\item
  The variable is a key (distinct values for each observation).
\end{itemize}

\fullline

\hypertarget{race}{\section{Race}\label{race}}

\bminione

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright\strut
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.18\columnwidth}\raggedleft\strut
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft\strut
factor\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft\strut
107 (10.7 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft\strut
7\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
Mode\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft\strut
``White''\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
Reference category\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft\strut
White\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\emini
\bminitwo
\includegraphics{dataMaid_report_files/figure-latex/Var-2-Race-1.pdf}
\emini

\begin{itemize}
\tightlist
\item
  Note that the following levels have at most five observations:
  "Other".
\end{itemize}

\fullline

\hypertarget{age}{\section{Age}\label{age}}

\bminione

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright\strut
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.18\columnwidth}\raggedleft\strut
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft\strut
character\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft\strut
122 (12.2 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft\strut
16\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
Mode\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft\strut
``21''\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\emini
\bminitwo
\includegraphics{dataMaid_report_files/figure-latex/Var-3-Age-1.pdf}
\emini

\begin{itemize}
\tightlist
\item
  Note: The variable consists exclusively of numbers and takes a lot of
  different values. Is it perhaps a misclassified numeric variable?
\end{itemize}

\fullline

\hypertarget{sex}{\section{Sex}\label{sex}}

\bminione

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright\strut
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.12\columnwidth}\raggedleft\strut
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft\strut
factor\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft\strut
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft\strut
2\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
Mode\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft\strut
``Male''\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
Reference category\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft\strut
Male\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\emini
\bminitwo
\includegraphics{dataMaid_report_files/figure-latex/Var-4-Sex-1.pdf}
\emini

\fullline

\hypertarget{height_cm_}{\section{Height\_cm\_}\label{height_cm_}}

\bminione

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright\strut
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.20\columnwidth}\raggedleft\strut
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft\strut
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft\strut
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft\strut
365\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
Median\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft\strut
175.3\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft\strut
168.2; 182.03\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft\strut
146.3; 207.2\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\emini
\bminitwo
\includegraphics{dataMaid_report_files/figure-latex/Var-5-Height-cm--1.pdf}
\emini

\begin{itemize}
\tightlist
\item
  Note that the following possible outlier values were detected:
  "201.1", "207.2".
\end{itemize}

\fullline

\hypertarget{iq}{\section{IQ}\label{iq}}

\bminione

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright\strut
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.18\columnwidth}\raggedleft\strut
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft\strut
numeric\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft\strut
102 (10.2 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft\strut
57\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
Median\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft\strut
100\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
1st and 3rd quartiles\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft\strut
93; 107\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
Min. and max.\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft\strut
68; 137\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\emini
\bminitwo
\includegraphics{dataMaid_report_files/figure-latex/Var-6-IQ-1.pdf}
\emini

\begin{itemize}
\tightlist
\item
  Note that the following possible outlier values were detected: "68",
  "129", "137".
\end{itemize}

\fullline

\hypertarget{smokes}{\section{Smokes}\label{smokes}}

\bminione

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright\strut
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.12\columnwidth}\raggedleft\strut
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft\strut
logical\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft\strut
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft\strut
2\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
Mode\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft\strut
``FALSE''\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\emini
\bminitwo
\includegraphics{dataMaid_report_files/figure-latex/Var-7-Smokes-1.pdf}
\emini

\fullline

\hypertarget{income}{\section{Income}\label{income}}

\bminione

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright\strut
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.16\columnwidth}\raggedleft\strut
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft\strut
factor\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft\strut
100 (10 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft\strut
900\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
Mode\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft\strut
``592.09''\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
Reference category\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft\strut
330.89\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\emini
\bminitwo
\includegraphics{dataMaid_report_files/figure-latex/Var-8-Income-1.pdf}
\emini

\begin{itemize}
\item
  Note that the following levels have at most five observations:
  "10093.41", "101416.01", "101711.6", "101922.46", "10209.53",
  "10309.37", "10360.78", "10368.95", "104430.62", "10611.98" (890
  additional values omitted).
\item
  Note: The variable consists exclusively of numbers and takes a lot of
  different values. Is it perhaps a misclassified numeric variable?
\end{itemize}

\fullline

\hypertarget{died}{\section{Died}\label{died}}

\bminione

\begin{longtable}[]{@{}lr@{}}
\toprule
\begin{minipage}[b]{0.34\columnwidth}\raggedright\strut
Feature\strut
\end{minipage} & \begin{minipage}[b]{0.12\columnwidth}\raggedleft\strut
Result\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
Variable type\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft\strut
logical\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
Number of missing obs.\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft\strut
0 (0 \%)\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
Number of unique values\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft\strut
2\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.34\columnwidth}\raggedright\strut
Mode\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft\strut
``TRUE''\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\emini
\bminitwo
\includegraphics{dataMaid_report_files/figure-latex/Var-9-Died-1.pdf}
\emini

\fullline

Report generation information:

\begin{itemize}
\item
  Created by Mateusz Staniak (username: \texttt{mstaniak}).
\item
  Report creation time: pt. mar 15 2019 15:44:48
\item
  Report was run from directory:
  \texttt{C:/Users/mstaniak/Projekty/MI2DataLab/autoEDA-resources/autoEDA-paper}
\item
  dataMaid v1.2.0 {[}Pkg: 2018-10-03 from CRAN (R 3.5.2){]}
\item
  R version 3.5.1 (2018-07-02).
\item
  Platform: x86\_64-w64-mingw32/x64 (64-bit)(Windows \textgreater{}= 8
  x64 (build 9200)).
\item
  Function call:
  \texttt{dataMaid::makeDataReport(data\ =\ example\_data,\ output\ =\ "pdf",\ \ file\ =\ "./plots/dataMaid/dataMaid\_report.pdf")}
\end{itemize}


\end{document}
